"""
Indianapolis Neighborhoods Data — Full List
Crime index: 1 (safest) → 10 (most dangerous)
Sources: NeighborhoodScout, IMPD Crime Stats, Redfin, Zillow
"""

NEIGHBORHOODS = [
    # ── VERY SAFE ────────────────────────────────────
    {
        "name": "Washington Township",
        "lat": 39.9100, "lng": -86.1400,
        "crime_index": 1, "crime_label": "Very Safe",
        "avg_price": 380000, "dom": 7, "zip": "46240",
        "notes": "North Indy elite area, top schools, luxury homes",
        "flip_rating": "⭐⭐", "rental_rating": "⭐⭐⭐⭐⭐",
    },
    {
        "name": "Meridian-Kessler",
        "lat": 39.8412, "lng": -86.1411,
        "crime_index": 2, "crime_label": "Very Safe",
        "avg_price": 345000, "dom": 8, "zip": "46208",
        "notes": "Upscale, historic homes, high demand, tree-lined streets",
        "flip_rating": "⭐⭐⭐", "rental_rating": "⭐⭐⭐⭐⭐",
    },
    {
        "name": "Castleton",
        "lat": 39.9020, "lng": -86.0560,
        "crime_index": 2, "crime_label": "Very Safe",
        "avg_price": 220000, "dom": 13, "zip": "46256",
        "notes": "NE suburb, shopping corridor, stable families",
        "flip_rating": "⭐⭐⭐", "rental_rating": "⭐⭐⭐⭐",
    },
    # ── SAFE ─────────────────────────────────────────
    {
        "name": "Broad Ripple",
        "lat": 39.8676, "lng": -86.1411,
        "crime_index": 3, "crime_label": "Safe",
        "avg_price": 285000, "dom": 12, "zip": "46220",
        "notes": "Trendy arts district, restaurants, young professionals",
        "flip_rating": "⭐⭐⭐", "rental_rating": "⭐⭐⭐⭐",
    },
    {
        "name": "SoBro",
        "lat": 39.8480, "lng": -86.1411,
        "crime_index": 3, "crime_label": "Safe",
        "avg_price": 255000, "dom": 11, "zip": "46220",
        "notes": "South of Broad Ripple, hot market, walkable",
        "flip_rating": "⭐⭐⭐⭐", "rental_rating": "⭐⭐⭐⭐",
    },
    {
        "name": "Butler-Tarkington",
        "lat": 39.8280, "lng": -86.1580,
        "crime_index": 3, "crime_label": "Safe",
        "avg_price": 290000, "dom": 9, "zip": "46208",
        "notes": "Near Butler University, stable, student rental demand",
        "flip_rating": "⭐⭐⭐", "rental_rating": "⭐⭐⭐⭐⭐",
    },
    {
        "name": "Rocky Ripple",
        "lat": 39.8550, "lng": -86.1700,
        "crime_index": 3, "crime_label": "Safe",
        "avg_price": 235000, "dom": 14, "zip": "46208",
        "notes": "Small quirky village feel, limited inventory",
        "flip_rating": "⭐⭐⭐", "rental_rating": "⭐⭐⭐",
    },
    # ── LOW-MEDIUM ────────────────────────────────────
    {
        "name": "Irvington",
        "lat": 39.7682, "lng": -86.0918,
        "crime_index": 4, "crime_label": "Low-Medium",
        "avg_price": 195000, "dom": 11, "zip": "46219",
        "notes": "Historic, charming, gentrifying, great flip area",
        "flip_rating": "⭐⭐⭐⭐", "rental_rating": "⭐⭐⭐⭐",
    },
    {
        "name": "Herron-Morton",
        "lat": 39.7890, "lng": -86.1530,
        "crime_index": 4, "crime_label": "Low-Medium",
        "avg_price": 230000, "dom": 10, "zip": "46202",
        "notes": "Near downtown, arts scene, rising values fast",
        "flip_rating": "⭐⭐⭐⭐", "rental_rating": "⭐⭐⭐⭐",
    },
    {
        "name": "Fountain Square",
        "lat": 39.7571, "lng": -86.1397,
        "crime_index": 4, "crime_label": "Low-Medium",
        "avg_price": 215000, "dom": 9, "zip": "46203",
        "notes": "Gentrifying fast, artists, young buyers, great ROI",
        "flip_rating": "⭐⭐⭐⭐⭐", "rental_rating": "⭐⭐⭐⭐",
    },
    {
        "name": "Speedway",
        "lat": 39.7920, "lng": -86.2480,
        "crime_index": 4, "crime_label": "Low-Medium",
        "avg_price": 155000, "dom": 15, "zip": "46224",
        "notes": "Home of Indy 500, affordable, stable community",
        "flip_rating": "⭐⭐⭐", "rental_rating": "⭐⭐⭐",
    },
    {
        "name": "Lawrence",
        "lat": 39.8390, "lng": -86.0250,
        "crime_index": 4, "crime_label": "Low-Medium",
        "avg_price": 185000, "dom": 16, "zip": "46226",
        "notes": "Northeast suburb, growing, affordable entry point",
        "flip_rating": "⭐⭐⭐", "rental_rating": "⭐⭐⭐",
    },
    {
        "name": "Beech Grove",
        "lat": 39.7220, "lng": -86.0920,
        "crime_index": 4, "crime_label": "Low-Medium",
        "avg_price": 168000, "dom": 14, "zip": "46107",
        "notes": "Independent city in Marion County, stable community",
        "flip_rating": "⭐⭐⭐⭐", "rental_rating": "⭐⭐⭐",
    },
    {
        "name": "Decatur Township",
        "lat": 39.6900, "lng": -86.2100,
        "crime_index": 4, "crime_label": "Low-Medium",
        "avg_price": 175000, "dom": 18, "zip": "46221",
        "notes": "Southwest, affordable family homes, quiet",
        "flip_rating": "⭐⭐⭐", "rental_rating": "⭐⭐⭐",
    },
    {
        "name": "Mapleton-Fall Creek",
        "lat": 39.8050, "lng": -86.1480,
        "crime_index": 5, "crime_label": "Medium",
        "avg_price": 175000, "dom": 17, "zip": "46205",
        "notes": "Transitional area, older homes, improving slowly",
        "flip_rating": "⭐⭐⭐", "rental_rating": "⭐⭐⭐",
    },
    # ── MEDIUM ────────────────────────────────────────
    {
        "name": "Bates-Hendricks",
        "lat": 39.7528, "lng": -86.1580,
        "crime_index": 5, "crime_label": "Medium",
        "avg_price": 165000, "dom": 14, "zip": "46225",
        "notes": "Up-and-coming, great flip potential, near downtown",
        "flip_rating": "⭐⭐⭐⭐⭐", "rental_rating": "⭐⭐⭐",
    },
    {
        "name": "Pike Township",
        "lat": 39.8700, "lng": -86.2400,
        "crime_index": 5, "crime_label": "Medium",
        "avg_price": 160000, "dom": 19, "zip": "46254",
        "notes": "Northwest, diverse population, schools improving",
        "flip_rating": "⭐⭐⭐", "rental_rating": "⭐⭐⭐",
    },
    {
        "name": "Crown Hill",
        "lat": 39.8020, "lng": -86.1780,
        "crime_index": 5, "crime_label": "Medium",
        "avg_price": 142000, "dom": 22, "zip": "46208",
        "notes": "Near famous cemetery, older homes, mixed area",
        "flip_rating": "⭐⭐⭐", "rental_rating": "⭐⭐⭐",
    },
    # ── MEDIUM-HIGH ───────────────────────────────────
    {
        "name": "Warren Township",
        "lat": 39.7600, "lng": -86.0400,
        "crime_index": 6, "crime_label": "Medium-High",
        "avg_price": 120000, "dom": 20, "zip": "46229",
        "notes": "Near Amazon warehouse, rental demand rising, affordable",
        "flip_rating": "⭐⭐⭐⭐", "rental_rating": "⭐⭐⭐⭐",
    },
    {
        "name": "Eagledale",
        "lat": 39.8130, "lng": -86.2220,
        "crime_index": 6, "crime_label": "Medium-High",
        "avg_price": 108000, "dom": 24, "zip": "46224",
        "notes": "West side, affordable, needs attention",
        "flip_rating": "⭐⭐⭐", "rental_rating": "⭐⭐",
    },
    {
        "name": "Forest Manor",
        "lat": 39.8200, "lng": -86.0800,
        "crime_index": 7, "crime_label": "High",
        "avg_price": 98000, "dom": 26, "zip": "46226",
        "notes": "Northeast, challenged area, very cheap entry",
        "flip_rating": "⭐⭐", "rental_rating": "⭐⭐",
    },
    # ── HIGH ──────────────────────────────────────────
    {
        "name": "Martindale-Brightwood",
        "lat": 39.8000, "lng": -86.1000,
        "crime_index": 9, "crime_label": "Very High",
        "avg_price": 72000, "dom": 38, "zip": "46218",
        "notes": "One of highest crime areas, extreme caution advised",
        "flip_rating": "⭐", "rental_rating": "⭐",
    },
    {
        "name": "Near Eastside",
        "lat": 39.7740, "lng": -86.1100,
        "crime_index": 8, "crime_label": "High",
        "avg_price": 95000, "dom": 28, "zip": "46201",
        "notes": "High crime, very cheap entry, high risk/reward",
        "flip_rating": "⭐⭐", "rental_rating": "⭐⭐",
    },
    {
        "name": "Near Westside / Haughville",
        "lat": 39.7740, "lng": -86.1900,
        "crime_index": 9, "crime_label": "Very High",
        "avg_price": 78000, "dom": 35, "zip": "46222",
        "notes": "Very high crime, gang activity, avoid for investment",
        "flip_rating": "⭐", "rental_rating": "⭐",
    },
    {
        "name": "Stringtown",
        "lat": 39.7400, "lng": -86.1750,
        "crime_index": 8, "crime_label": "High",
        "avg_price": 85000, "dom": 30, "zip": "46225",
        "notes": "South side, high crime, some gentrification starting",
        "flip_rating": "⭐⭐", "rental_rating": "⭐⭐",
    },
    {
        "name": "Cole Noble",
        "lat": 39.7850, "lng": -86.1750,
        "crime_index": 8, "crime_label": "High",
        "avg_price": 82000, "dom": 33, "zip": "46222",
        "notes": "West side, persistent crime issues, very low prices",
        "flip_rating": "⭐", "rental_rating": "⭐⭐",
    },
    {
        "name": "Near Northside",
        "lat": 39.7960, "lng": -86.1570,
        "crime_index": 7, "crime_label": "High",
        "avg_price": 110000, "dom": 25, "zip": "46202",
        "notes": "Just north of downtown, transitional, improving slowly",
        "flip_rating": "⭐⭐⭐", "rental_rating": "⭐⭐",
    },
    {
        "name": "Riverside",
        "lat": 39.8100, "lng": -86.1900,
        "crime_index": 7, "crime_label": "High",
        "avg_price": 105000, "dom": 27, "zip": "46208",
        "notes": "Near White River, high crime, cheap but risky",
        "flip_rating": "⭐⭐", "rental_rating": "⭐⭐",
    },
    {
        "name": "Fall Creek Place",
        "lat": 39.7980, "lng": -86.1400,
        "crime_index": 6, "crime_label": "Medium-High",
        "avg_price": 195000, "dom": 15, "zip": "46205",
        "notes": "Planned redevelopment area, improving, mixed results",
        "flip_rating": "⭐⭐⭐", "rental_rating": "⭐⭐⭐",
    },
    # ── NEAR AIRPORT ─────────────────────────────────
    {
        "name": "Eagle Creek",
        "lat": 39.8300, "lng": -86.2800,
        "crime_index": 3, "crime_label": "Safe",
        "avg_price": 210000, "dom": 16, "zip": "46254",
        "notes": "Near Eagle Creek Park & reservoir, quiet suburban feel",
        "flip_rating": "⭐⭐⭐", "rental_rating": "⭐⭐⭐⭐",
    },
    {
        "name": "Ben Davis / West Indy",
        "lat": 39.7800, "lng": -86.2700,
        "crime_index": 6, "crime_label": "Medium-High",
        "avg_price": 118000, "dom": 22, "zip": "46214",
        "notes": "West side near airport, affordable, mixed crime",
        "flip_rating": "⭐⭐⭐", "rental_rating": "⭐⭐⭐",
    },
    {
        "name": "Mars Hill",
        "lat": 39.7500, "lng": -86.2850,
        "crime_index": 7, "crime_label": "High",
        "avg_price": 92000, "dom": 30, "zip": "46221",
        "notes": "Southwest near airport, high crime, very cheap entry",
        "flip_rating": "⭐⭐", "rental_rating": "⭐⭐",
    },
    {
        "name": "Bridgeport",
        "lat": 39.7150, "lng": -86.2600,
        "crime_index": 5, "crime_label": "Medium",
        "avg_price": 145000, "dom": 20, "zip": "46231",
        "notes": "Near airport & FedEx hub, rental demand from airport workers",
        "flip_rating": "⭐⭐⭐", "rental_rating": "⭐⭐⭐⭐",
    },
    {
        "name": "Airport / Camby Area",
        "lat": 39.6980, "lng": -86.3100,
        "crime_index": 3, "crime_label": "Safe",
        "avg_price": 198000, "dom": 17, "zip": "46113",
        "notes": "Southwest suburb, near IND airport, growing logistics hub",
        "flip_rating": "⭐⭐⭐", "rental_rating": "⭐⭐⭐⭐",
    },
    {
        "name": "Clermont",
        "lat": 39.8050, "lng": -86.3050,
        "crime_index": 4, "crime_label": "Low-Medium",
        "avg_price": 162000, "dom": 18, "zip": "46234",
        "notes": "Far west, quiet, near Eagle Creek, family-friendly",
        "flip_rating": "⭐⭐⭐", "rental_rating": "⭐⭐⭐",
    },
    {
        "name": "Downtown Indianapolis",
        "lat": 39.7684, "lng": -86.1581,
        "crime_index": 6, "crime_label": "Medium-High",
        "avg_price": 280000, "dom": 18, "zip": "46204",
        "notes": "Condos & apartments, high foot traffic, mixed crime",
        "flip_rating": "⭐⭐", "rental_rating": "⭐⭐⭐⭐⭐",
    },
    {
        "name": "Garfield Park",
        "lat": 39.7350, "lng": -86.1480,
        "crime_index": 6, "crime_label": "Medium-High",
        "avg_price": 138000, "dom": 16, "zip": "46203",
        "notes": "South side near park, improving, some gentrification",
        "flip_rating": "⭐⭐⭐⭐", "rental_rating": "⭐⭐⭐",
    },
    {
        "name": "University Heights",
        "lat": 39.7820, "lng": -86.1200,
        "crime_index": 5, "crime_label": "Medium",
        "avg_price": 148000, "dom": 17, "zip": "46218",
        "notes": "East side, near IUPUI corridor, workforce housing",
        "flip_rating": "⭐⭐⭐", "rental_rating": "⭐⭐⭐",
    },
]
